language: java

java:
  - jdk-9.0.1
  
install:
  - gradle assemble

after_success:
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/1.0.13/codacy-coverage-reporter-2.0.1-assembly.jar -O ccr.jar
  - java -cp ccr.jar com.codacy.CodacyCoverageReporter -l Java -r ./resteasy-spring-boot-starter/target/site/cobertura/coverage.xml --projectToken 7afdc2a8c38b41aab4894c1d5332ffbe

services:
  - postgresql
  
script:
  - test \lab_db\src\labTests\MainTest.java
