language: java

java:
  - jdk-9.0.1
begore_install:
     - wget -O ~/codacy-coverage-reporter-assembly.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.1/codacy-coverage-reporter-2.0.1-assembly.jar
install:
  - gradle assemble

after_success:
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/2.0.1/codacy-coverage-reporter-2.0.1-assembly.jar -O ccr.jar
  - java -cp codacy-coverage-reporter-2.0.1-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml
  - export CODACY_PROJECT_TOKEN=7afdc2a8c38b41aab4894c1d5332ffbe
  - codacy-coverage-reporter -l Java --commitUUID "mycommituuid" -r coverage.xml
  - codacy-coverage-reporter -l Java -r coverage.xml

services:
  - postgresql
  
script:
  - test \lab_db\src\labTests\MainTest.java
